<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="126" started-at="2019-11-15T10:23:48Z" finished-at="2019-11-15T10:23:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="126" started-at="2019-11-15T10:23:48Z" finished-at="2019-11-15T10:23:48Z">
      <class name="com.Framework.moven_moduleTest.CreateTest">
        <test-method status="PASS" signature="abalidatecustomerTest()[pri:0, instance:com.Framework.moven_moduleTest.CreateTest@546a03af]" name="abalidatecustomerTest" duration-ms="50" started-at="2019-11-15T15:53:48Z" finished-at="2019-11-15T15:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- abalidatecustomerTest -->
        <test-method status="PASS" signature="avalidatecustomerTest()[pri:1, instance:com.Framework.moven_moduleTest.CreateTest@546a03af]" name="avalidatecustomerTest" duration-ms="2" started-at="2019-11-15T15:53:48Z" finished-at="2019-11-15T15:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- avalidatecustomerTest -->
        <test-method status="FAIL" signature="avalidatecustomeraTest()[pri:2, instance:com.Framework.moven_moduleTest.CreateTest@546a03af]" name="avalidatecustomeraTest" duration-ms="8" started-at="2019-11-15T15:53:48Z" finished-at="2019-11-15T15:53:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ravi] but found [Ravi]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ravi] but found [Ravi]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.Framework.moven_moduleTest.CreateTest.avalidatecustomeraTest(CreateTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- avalidatecustomeraTest -->
      </class> <!-- com.Framework.moven_moduleTest.CreateTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
